### ISSUE TITLE
Repository path '/git/.../' is not owned by current user

### ISSUE THREAD

**Issue by orzklv** [w4/rgit#10]
**Tried to host docker image of rgit using this command:**
```shell
docker run --mount type=bind,source=/srv/repos,target=/git -it -d --restart always -p 3001:8000 ghcr.io/w4/rgit:main
```

**And got this error:**
```2023-08-19T22:13:40.672579Z  INFO index_update: rgit::database::indexer: Starting index update
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -36, klass: 7, message: "repository path '/git/orzklv-dots/' is not owned by current user" }', src/database/indexer.rs:47:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by stappersg** [comment]
> ```
> Error { code: -36, klass: 7,
>      message: "repository path '/git/orzklv-dots/' 
>                  is not owned by current user" }', 
> ```

The `README.md` has this:

_Your `SCAN_PATH` should contain (optionally nested) [bare repositories](https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server), and a `config` file
can be written with a `[gitweb.owner]` key to signify ownership._

That might be a _clue_ to solve this issue.

I do have _bare repositories_ but don't know where to put `config` file with `[gitweb.owner]` key.

This is what I get: 

![Empty view](https://github.com/w4/rgit/assets/35434094/980d5a47-c7ae-431d-a288-cea3c1923dca)

An _empty view_ ...

I do hope that _"a `config` file can be written with a `[gitweb.owner]` key to signify ownership"_ gets elaborated.

**Comment by w4** [comment]
`[gitweb.owner]` is for that `Owner` column in the table. Here's `rgit.git/config` on git.inept.dev for example:

```
❯ cat config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = true
[remote "origin"]
        url = https://github.com/w4/rgit
        fetch = +refs/*:refs/*
        mirror = true
[gitweb]
        owner = Jordan Doyle
```

The error here seems to be a unix permissions problem. I'm not a Docker user myself so I don't know exactly how to mount files in the container using the docker user as the owner. Perhaps it's just a matter of dropping `USER nobody` from [the Dockerfile](https://github.com/w4/rgit/blob/main/Dockerfile#L13). Will take a look later on today.

**Comment by stappersg** [comment]
Tail of _Docker file_
```
USER nobody
EXPOSE 8000
ENTRYPOINT ["/rgit", "[::]:8000", "/git", "-d", "/tmp/rgit-cache.db"]
```

This issue:
```
docker run --mount type=bind,source=/srv/repos,target=/git \
  -it -d --restart always -p 3001:8000 ghcr.io/w4/rgit:main
```

```
Error { code: -36, klass: 7,
message: "repository path '/git/orzklv-dots/' is not owned by current user" }',
src/database/indexer.rs:47:79
```

and
> Perhaps it's just a matter of dropping `USER nobody` from the Dockerfile.

What I think:  The _docker `USER`_ should have an _user id_ that matches the _user id_ of the owner of `/srv/repos` at the Docker host.

What I further think:
* `www-data` might work.
* Dropping `USER nobody` from dockerfile might work.
* It might be a good thing if those who don't understand _Docker_, didn't use _Docker_.

For what it is worth:
```text
$ id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
$ 
```

**Comment by stappersg** [comment]
It is not _Docker_ related.  Outside _Docker_ I get also the
```
message: "repository path '/srv/git/projectname.git/' is not owned by current user"
```

It is [_a git thing_](https://duckduckgo.com/?q=git+repository+is+not+owned+by+current+user), not something specific to `rgit`.

I think it is a good design choice of the creators of `git`: _The only one who writes to a repository is the owner_.

**Comment by orzklv** [comment]
The issue has been resolved by passing UID of user to docker container. Thanks all for the support & help!
