### ISSUE TITLE
Wish: Provide a  `favicon.ico`.

### ISSUE THREAD

**Issue by stappersg** [w4/rgit#13]
Hello,

In the logging of `rgit` I do get
```text
ERROR web{request_id="4fa1b772-f0af-484e-9bb2-af8460a7826f"}: 
  rgit::layers::logger: [::ffff:192.168.24.36]:35888
   - "GET /favicon.ico" 500 122.979µs
   "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "Ok(())"
```

My wish is that `rgit` provides a _favicon.ico_, it will prevent error entries in the logging.

I did
```bash
cd statics
curl https://git-scm.com/favicon.ico > favicon.ico
```
and a _`cargo run`_, but again got the error.

Where to put a `favicon.ico` so it can be served to webbrowsers?

**Comment by w4** [comment]
The missing piece of the puzzle is a route for favicon.ico here: https://github.com/w4/rgit/blob/main/src/main.rs#L109

**Comment by stappersg** [comment]
> missing piece of the puzzle is a route for favicon.ico 

Thanks

There is now [https://github.com/w4/rgit/pull/14](https://github.com/w4/rgit/pull/14).

No need to keep this issue open, closing it.
