### ISSUE TITLE
Allow automatic index refresh to be a variable

### ISSUE THREAD

**Issue by graskaas** [w4/rgit#21]
Automatic index refreshing is done every 300 seconds, or 5 minutes. While ideal for normal operations, smaller operations don't need as much refreshing. I personally push my updates at the end of each day, so setting a refresh time for 12 hours would be my use case.

(also useful for testing purposes as I wouldn't have to start and stop a container every time I add a new repo but thats neither here nor there...)

I propose:

Command line args:
`--refresh TIME`

Environment variable (for scripts and docker)
`RGIT_REFRESH_TIME = TIME`

where TIME is in seconds (as is the current behavior)

This would not be a breaking change if 300 is the default for `--refresh`.

**Comment by stappersg** [comment]
Yeah, the _"refresh index every five minutes"_  deserves some rethinking, so some questions:

* Why is it part of _web interface_?
* What about having separate _"index refresher"_?

**Comment by graskaas** [comment]
> What about having separate _"index refresher"_?

I the idea of having refresh separate more than allowing the software to auto refresh, you have a good point there.
 
Revision:
```zsh
rgit /path/to/my-repos -d /tmp/rgit-cache.db --refresh
```

It would only refresh the database and then exit, leaving the existing running server uninterrupted.

Use cases:

- automatic refreshes run from `cron` jobs
- repos are on a shared mount drive, and another server would handle the refresh in situations where the web server is under heavy load.
- manual refresh when adding or removing repos

I am also considering being able to monitor the repos directory for changes and trigger a refresh from there. That would allow me to to use `entr`  to do that.

https://github.com/eradman/entr

**Comment by stappersg** [comment]
Idea:
```diff
--- a/src/main.rs
+++ b/src/main.rs
@@ -129,6 +129,7 @@ async fn main() {
             "/favicon.ico",
             get(static_favicon(include_bytes!("../statics/favicon.ico"))),
         )
+        .route("/reindex", put(internal_refresh_index())
         .fallback(methods::repo::service)
         .layer(layer_fn(LoggingMiddleware))
         .layer(Extension(Arc::new(Git::new(syntax_set))))
```
Example for requesting the _refresh index_
```text
curl --request PUT --data "key=it_is_me" http://rgit.host/reindex
```
Where `it_is_me` is some kind of _secret_ that helps preventing that everybody with access to `rgit.host` triggers refreshes (avoiding Denial of Service vulnerability).

Triggering the _refresh index request_ could be done with `.git/hooks/post-update`.

**Comment by graskaas** [comment]
Wouldn't accepting a `PUT` request introduce an attack surface? If it can be guaranteed that:

- No database injection attacks are possible
- There are no more CVEs in `axum` [like this one](https://rustsec.org/advisories/RUSTSEC-2022-0055.html)
- Is optional

I think would be a good addition.

**Comment by w4** [comment]
Reindexing is quite heavy so without heavy rate limiting I'd be worried about exposing it from the API. I like the idea of allowing a `--refresh` flag to reindex the database, but afaik Sled holds a lock over the database. Maybe a `--no-reindex` flag and allowing a signal to be sent to the application (`kill -SIGHUP`) to refresh would be a suitable solution?
