### ISSUE TITLE
BUG: branch view parameter "h=xxx" does not carry over to tree and plain and other views

### ISSUE THREAD

**Issue by darkclip** [w4/rgit#44]
when click into branch or ref, param h is added to indicate current branch, but when in the branch other than master, click other views, the parameter is not automatically carry over to that page, have to manually put the param to get to the branch view.

**Comment by w4** [comment]
Thanks for the report. Fixed by https://github.com/w4/rgit/commit/39bdc18d9982b21db2ca64e6173d495d37e793ed
