### ISSUE TITLE
feature request: able to git clone through repo's URL link

### ISSUE THREAD

**Issue by darkclip** [w4/rgit#49]
It appears in cgit, you can clone the repo through the URL link, it would be nice to have the same function in your project too.

**Comment by w4** [comment]
This should already work, try `git clone https://git.inept.dev/~doyle/rgit.git`.

**Comment by darkclip** [comment]
oh, I see, indeed I'm using docker image,  maybe I need to update that legacy image, but I definitely not seeing the `git-daemon-export-ok` file requirement for that to work. I think this issue can be closed.
