### ISSUE TITLE
[BUG] clone through http fail on some repo

### ISSUE THREAD

**Issue by darkclip** [w4/rgit#56]
I mirrored some repo to my server, and most of them clone through http fine.
But I encountered this one: `pyenv/pyenv`, clone through http gave me `fatal: the remote end hung up unexpectedly`.
Already tried deleting the repo and re-mirror, same result, so I think there's a bug some where in rgit.

**Comment by stappersg** [comment]
On Fri, Feb 02, 2024 at 10:42:34AM -0800, DC wrote:
>   ..., so I think there's a bug some where in rgit.

I think I should delete this comment.

I think also that it doesn't matter what I think.

What matters is what I **do**.
Like sharing this link http://www.catb.org/esr/faqs/smart-questions.html#idm368

**Comment by darkclip** [comment]
> On Fri, Feb 02, 2024 at 10:42:34AM -0800, DC wrote: ..., so I think there's a bug some where in rgit.
> I think I should delete this comment. I think also that it doesn't matter what I think. What matters is what I **do**. Like sharing this link http://www.catb.org/esr/faqs/smart-questions.html#idm368

There's no need for the sarcasm, I use the phrase I think is because I didn't rule out the reverse proxy in front of rgit.
Since you mentioned that I should be more sure of the root of this issue, I just tested a direct connection to rgit.
Now I'm sure the cause of the problem is indeed rgit itself.

**Comment by w4** [comment]
Thanks for the report, it is indeed a bug. It has been fixed in https://github.com/w4/rgit/commit/96928a28c708f08e2c64047ee314d77016a394ce
